### ISSUE TITLE
Add support for several urls per src

### ISSUE THREAD

**Issue by florian-lefebvre** [rishi-raj-jain/astro-font#10]
How to achieve this with your package?
```css
@font-face {
  font-family: "Deacon Black";
  src:
    url("/assets/fonts/Deacon-Black.woff2") format("woff2"),
    url("/assets/fonts/Deacon-Black.woff") format("woff");
  font-weight: 900;
  font-style: normal;
  font-display: swap;
}
```
